---
- name: Setup SSHD for Ansible Access
  hosts: all
  become: true
  vars:
    user_var: "derek"
    public_key_var: "YOUR_PUBLIC_SSH_KEY_HERE" # Replace with your actual public key

  tasks:
    - name: Ensure SSH server is installed
      ansible.builtin.apt:
        name: openssh-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure SSH server is installed
      ansible.builtin.dnf:
        name: openssh-server
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure SSH service is running and enabled
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true

#    - name: Configure SSHD to allow public key authentication
#      ansible.builtin.lineinfile:
#        path: /etc/ssh/sshd_config
#        regexp: "^#?PasswordAuthentication"
#        line: "PasswordAuthentication no"
#        state: present
#        backup: true

#    - name: Configure SSHD to allow key-based login
#      ansible.builtin.lineinfile:
#        path: /etc/ssh/sshd_config
#        regexp: "^#?PubkeyAuthentication"
#        line: "PubkeyAuthentication yes"
#        state: present
#        backup: true

    - name: Ensure the ansible user exists
      ansible.builtin.user:
        name: "{{ user_var }}"
        state: present
        shell: /bin/bash

    - name: Add the ansible user to the wheel group
      ansible.builtin.user:
        name: "{{ user_var }}"
        groups: wheel
        append: true

    - name: Create .ssh directory for ansible user
      ansible.builtin.file:
        path: "/home/{{ user_var }}/.ssh"
        state: directory
        owner: "{{ user_var }}"
        group: "{{ user_var }}"
        mode: '0700'

    - name: Add authorized key for ansible user
      ansible.builtin.copy:
        content: "{{ public_key_var }}"
        dest: "/home/{{ user_var }}/.ssh/authorized_keys"
        owner: "{{ user_var }}"
        group: "{{ user_var }}"
        mode: '0600'

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: sshd
        state: restarted
